# Generated by Django 4.2.2 on 2023-07-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='img_caption',
            field=models.CharField(default='Credit', max_length=200),
        ),
        migrations.AlterField(
            model_name='reports',
            name='report_img',
            field=models.ImageField(default='default.png', null=True, upload_to='images/'),
        ),
    ]
