# Generated by Django 4.2.2 on 2023-08-03 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_reports_img_caption_alter_reports_report_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='admin_approved',
            field=models.BooleanField(default=False),
        ),
    ]
